export const skillsDetails = [
  {
    id: 1,
    title: "Javascript",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 2,
    title: "Typescript",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  { id: 3, title: "Java", value: 95, value_label: "95%", years: "3 Years" },
  { id: 4, title: "React", value: 95, value_label: "95%", years: "4 Years" },
  { id: 5, title: "Angular", value: 90, value_label: "90%", years: "3 Years" },
  {
    id: 6,
    title: "HTML & CSS",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 7,
    title: "Node JS & Express",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 8,
    title: "Serverless",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
];
export const skillDetails2 = [
  {
    id: 9,
    title: "AWS Lambda",
    value: 95,
    value_label: "95%",
    years: "2 Years",
  },
  {
    id: 10,
    title: "AWS Amplify",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 11,
    title: "AWS API gateway",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  {
    id: 12,
    title: "Terraform",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },

  {
    id: 13,
    title: "AWS Cognito",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  { id: 14, title: "AWS S3", value: 95, value_label: "95%", years: "3 Years" },
  {
    id: 15,
    title: "Cloudwatch",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  { id: 16, title: "EC2", value: 95, value_label: "95%", years: "3 Years" },
];

export const skillDetails3 = [
  {
    id: 17,
    title: "MySQL,SQlserver",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  { id: 18, title: "MongoDB", value: 95, value_label: "95%", years: "4 Years" },
  {
    id: 19,
    title: "Sequelize",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  {
    id: 20,
    title: "Db Indexing",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  { id: 21, title: "DBMS", value: 95, value_label: "95%", years: "4 Years" },
  {
    id: 22,
    title: "Git, Github",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 23,
    title: "Jenkins, Github Actions",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  { id: 24, title: "Docker", value: 95, value_label: "95%", years: "4 Years" },
];

export const skillsDetailsAll = [
  {
    id: 1,
    title: "Javascript",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 2,
    title: "Typescript",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  { id: 3, title: "Java", value: 95, value_label: "95%", years: "3 Years" },
  { id: 4, title: "React", value: 95, value_label: "95%", years: "4 Years" },
  { id: 5, title: "Angular", value: 90, value_label: "90%", years: "3 Years" },
  {
    id: 6,
    title: "HTML & CSS",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 7,
    title: "Node JS & Express",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 8,
    title: "Serverless",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  {
    id: 9,
    title: "AWS Lambda",
    value: 95,
    value_label: "95%",
    years: "2 Years",
  },
  {
    id: 10,
    title: "AWS Amplify",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },
  {
    id: 11,
    title: "AWS API gateway",
    value: 95,
    value_label: "95%",
    years: "3 Years",
  },
  {
    id: 12,
    title: "Terraform",
    value: 95,
    value_label: "95%",
    years: "4 Years",
  },

  // {
  //   id: 13,
  //   title: "AWS Cognito",
  //   value: 95,
  //   value_label: "95%",
  //   years: "3 Years",
  // },
  // { id: 14, title: "AWS S3", value: 95, value_label: "95%", years: "3 Years" },
  // {
  //   id: 15,
  //   title: "Cloudwatch",
  //   value: 95,
  //   value_label: "95%",
  //   years: "3 Years",
  // },
  // { id: 16, title: "EC2", value: 95, value_label: "95%", years: "3 Years" },

  // {
  //   id: 17,
  //   title: "MySQL,SQlserver",
  //   value: 95,
  //   value_label: "95%",
  //   years: "4 Years",
  // },
  // { id: 18, title: "MongoDB", value: 95, value_label: "95%", years: "4 Years" },
  // {
  //   id: 19,
  //   title: "Sequelize",
  //   value: 95,
  //   value_label: "95%",
  //   years: "3 Years",
  // },
  // {
  //   id: 20,
  //   title: "Db Indexing",
  //   value: 95,
  //   value_label: "95%",
  //   years: "3 Years",
  // },
  // { id: 21, title: "DBMS", value: 95, value_label: "95%", years: "4 Years" },
  // {
  //   id: 22,
  //   title: "Git, Github",
  //   value: 95,
  //   value_label: "95%",
  //   years: "4 Years",
  // },
  // {
  //   id: 23,
  //   title: "Jenkins, Github Actions",
  //   value: 95,
  //   value_label: "95%",
  //   years: "4 Years",
  // },
  // { id: 24, title: "Docker", value: 95, value_label: "95%", years: "4 Years" },
];
